[book]
title        = "The Rust on ESP Book 简体中文版"
description  = "A comprehensive guide on using the Rust programming language with Espressif SoCs and modules"
language     = "zh-CN"

[rust]
edition = "2024"

[output.html]
git-repository-url = "https://github.com/Narukara/rust-on-esp-book-zh-cn"
